version: '2'
services:
  web:
    image: netzkollektivgmbh/docker-magento2
    ports:
      - "80:80"
    links:
      - db
      - redis
      - mail
    env_file:
      - env
    volumes:
      - ../magento2:/var/www/html
    static-network:
        ipv4_address: 172.18.0.3

  db:
    image: mysql:5.6
    env_file:
      - env
    static-network:
        ipv4_address: 172.18.0.7

  redis:
    image: redis
    ports:
      - 6379

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
